### ISSUE TITLE
Security concerns

### ISSUE THREAD

**Issue by gselis** [shrocky2/GarageWeb#1]
- Currently, the password can be brute-forced. An mechanism should be put in place to prevent brute-forcing/guessing the password. Perhaps this could be done by blocking requests from the originating IP address, or blocking all requests for increasingly longer periods of time.

- The web site should use HTTPS to prevent MITM (man in the middle) attacks, where a clear-text password could be intercepted by a malicious actor.

**Comment by agrrajag** [comment]
Hey @shrocky2, I found your project because your project was featured in an [article on Tom's Hardware](https://www.tomshardware.com/features/best-raspberry-pi-projects-may-2020)

I agree that a brute-force protection would be good... not sure if I can provide any additional input to that yet.

For HTTPS, I have a little guide on setting up an HTTPS Nginx reverse proxy on your pi if you want me to fork it over to you. This will turn port 443 traffic from outside to 5000 locally and should satisfy the demand to encrypt passwords in transit. I would also enable and configure ufw to only allow the traffic through that you want (likely HTTPS 443 and SSH 22)

**Comment by shrocky2** [comment]
My new mulitdoor setup with Siri support is complete and live on GitHub and YouTube. This new project allows for up to 3 doors and has added security to prevent bad passwords. After 5 bad passwords, the system shuts down until the pi is rebooted. I have no knowledge on how to get HTTPS to work as it would require a security certificate...and this was just a fun project.

You can use the same hardware setup as this project, just need to download the new code. Find the code here: https://github.com/shrocky2/SiriGarage || YouTube Video Instructions found here: https://youtu.be/wfsYFM-9Dns
